const projects={
edgeguard:{eyebrow:"Embedded AI • Colibry NPU • Computer Vision",title:"EdgeGuard — Embedded AI on Colibry",desc:"Real-time human and animal detection using edge AI, computer vision and the Colibry hardware platform.",overview:"EdgeGuard is the main embedded AI project. The Colibry board and its NPU/SDK work are part of the same project, providing the hardware acceleration and embedded deployment platform.",architecture:"Camera\n  ↓\nColibry Hardware\n  ↓\nImage preprocessing\n  ↓\nYOLO / ONNX\n  ↓\nAIDGE / NPU acceleration\n  ↓\nHuman + Animal Detection\n  ↓\nLive Dashboard",tech:["Colibry Board","NPU","RISC-V","Python","Linux","OpenCV","YOLOv8","ONNX","AIDGE","Computer Vision"],challenges:"The project includes embedded SDK setup, model import, inference validation, preprocessing/postprocessing and hardware-specific optimization.",future:"Real-time tracking, additional animal classes, NPU performance benchmarking, lower latency and a fully integrated live monitoring dashboard.",github:"#",status:"In active development",focus:"Human + animal detection",platform:"Colibry + edge hardware",objective:"Build a practical edge-AI vision pipeline that can perform object detection close to the camera instead of depending on a cloud inference service.",pipeline:"Camera\n  ↓\nPreprocessing\n  ↓\nYOLOv8 / ONNX\n  ↓\nAIDGE runtime\n  ↓\nNPU / hardware acceleration\n  ↓\nDetection + monitoring",implementation:"The project currently includes the Colibry/NPU environment work, AIDGE setup, ONNX model loading and inference validation. Performance benchmarking and the complete real-time detection pipeline are still being developed."},
gesture:{eyebrow:"Computer Vision • Deep Learning",title:"Gesture Recognition CNN",desc:"Real-time hand gesture recognition using camera input, computer vision and a CNN model.",overview:"A complete gesture-recognition pipeline covering dataset collection, model training, camera inference and Raspberry Pi deployment.",architecture:"Camera\n  ↓\nOpenCV\n  ↓\nImage preprocessing\n  ↓\nCNN Model\n  ↓\nGesture prediction\n  ↓\nLive Dashboard",tech:["Python","OpenCV","CNN","TensorFlow / TFLite","MediaPipe","Raspberry Pi"],challenges:"Camera selection, real-time inference and reliable gesture classification were handled while keeping the system suitable for edge hardware.",future:"More gestures, improved model accuracy, latency/FPS monitoring and tighter Raspberry Pi dashboard integration.",github:"https://github.com/nagaraju072001-design/Gesture-Recognition-CNN",status:"Prototype / deployment development",focus:"Real-time gesture recognition",platform:"Raspberry Pi + camera",objective:"Recognize a defined set of hand gestures from live camera input using a lightweight computer-vision and CNN pipeline suitable for edge deployment.",pipeline:"Camera\n  ↓\nOpenCV / MediaPipe\n  ↓\nPreprocessing\n  ↓\nCNN / TensorFlow Lite\n  ↓\nGesture prediction\n  ↓\nLive interface",implementation:"The project covers dataset collection, image preprocessing, CNN-based recognition and camera inference. The current gesture set includes Fist, OK, Palm, Peace and Thumb Up."}
};
const home=document.querySelectorAll(".home"),detail=document.getElementById("detail");
function openProject(id){const p=projects[id];if(!p)return;home.forEach(x=>x.classList.add("hidden"));detail.classList.add("active");document.getElementById("dEyebrow").textContent=p.eyebrow;document.getElementById("dTitle").textContent=p.title;document.getElementById("dDesc").textContent=p.desc;document.getElementById("overview").textContent=p.overview;document.getElementById("objective").textContent=p.objective;document.getElementById("pipeline").textContent=p.pipeline;document.getElementById("implementation").textContent=p.implementation;document.getElementById("dStatus").textContent=p.status;document.getElementById("dFocus").textContent=p.focus;document.getElementById("dPlatform").textContent=p.platform;document.getElementById("architecture").textContent=p.architecture;document.getElementById("challenges").textContent=p.challenges;document.getElementById("future").textContent=p.future;document.getElementById("tech").innerHTML=p.tech.map(x=>'<span class="tag">'+x+'</span>').join("");const g=document.getElementById("github");g.href=p.github;g.style.display=p.github==="#"?"none":"inline-flex";window.scrollTo({top:0,behavior:"smooth"});}
function closeProject(){detail.classList.remove("active");home.forEach(x=>x.classList.remove("hidden"))}
document.querySelectorAll("[data-project]").forEach(c=>c.addEventListener("click",()=>{location.hash="project/"+c.dataset.project}));
window.addEventListener("hashchange",()=>{const h=location.hash;if(h.startsWith("#project/"))openProject(h.split("/")[1]);else closeProject()});
if(location.hash.startsWith("#project/"))openProject(location.hash.split("/")[1]);
